export type SiteData = {
  artistName: string;
  subtitle?: string;
  catchcopy?: string;
  heroImage?: string;
  profileImage?: string;
  bio?: string;
  motto?: string;
  location?: string;
  artStyle?: string;
  tools?: string[];
  stats?: string[];
  skills?: string[];
  email?: string;
  works: { src: string; title: string }[];
  snsX?: string;
  snsInstagram?: string;
  snsPixiv?: string;
  snsNote?: string;
  snsOther?: string;
};
