// Generated by しくみや — 2026-04-07T08:11:31.532Z
export const siteConfig = {
  name: "Sora",
  siteTitle: "adsdsasda",
  description: "xdscvSDVsvszdvsdvszvs",
  url: "",
  lang: "ja",
  template: "comic-panel",

  colors: {
    primary: "#00e5ff",
    accent: "#d4a853",
    background: "#0a0a0f",
  },

  hero: {
    tagline: "Gallery",
    catchcopy: "sdasdsadasdas",
    motto: "SDSDVsd",
    subtitle: "Art Portfolio",
    description: "xdscvSDVsvszdvsdvszvs",
    backgroundImage: "/images/hero.webp",
    cta: {
      text: "作品を見る",
      href: "#gallery",
    },
  },

  gallery: {
    title: "GALLERY",
    subtitle: "作品ギャラリー",
    description: "",
    works: [
    { src: "/images/work_01.webp", title: "作品 01", description: "" },
    { src: "/images/work_02.webp", title: "作品 02", description: "" },
    { src: "/images/work_03.webp", title: "作品 03", description: "" },
    { src: "/images/work_04.webp", title: "作品 04", description: "" },
    { src: "/images/work_05.webp", title: "作品 05", description: "" },
    { src: "/images/work_06.webp", title: "作品 06", description: "" },
    { src: "/images/work_07.webp", title: "作品 07", description: "" },
    { src: "/images/work_08.webp", title: "作品 08", description: "" },
    ],
    initialDisplay: 8,
  },

  about: {
    title: "ABOUT",
    subtitle: "アーティストについて",
    image: "/images/about.webp",
    paragraphs: ["xdscvSDVsvszdvsdvszvs"],
    quote: "SDSDVsd",
    genres: [],
    tools: ["SDvSvSADv","ADSvADSDv"],
  },

  contact: {
    title: "CONTACT",
    subtitle: "お問い合わせ・SNS",
    description: "お仕事のご依頼・コラボレーション・ご質問はお気軽にどうぞ。",
    email: "ryoya112@outlook.com",
    social: [
    { label: "X (Twitter)", href: "https://x.com/sora_manga_test" },
    { label: "Instagram", href: "https://instagram.com/sora_manga_test" },
    ] as { label: string; href: string }[],
  },

  nav: [
    { label: "Gallery", href: "#gallery" },
    { label: "About", href: "#about" },
    { label: "Contact", href: "#contact" },
  ],

  footer: {
    credit: "Built with Next.js — Template by しくみや",
    copyright: `© ${new Date().getFullYear()} Sora. All rights reserved.`,
  },
};

export type SiteConfig = typeof siteConfig;
